services:
  reverse_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./msecurity.conf:/etc/nginx/modsec/msecurity.conf
      - ./403.html:/etc/nginx/html/403.html 
  bwapp:  
    image: hackersploit/bwapp-docker
    container_name: bwapp
    hostname: bwapp